/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CutImageModal: typeof import('./src/components/CutImageModal.vue')['default']
    MyUpload: typeof import('./src/components/MyUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
